/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScreenerRouteImport } from './routes/_app.screener'
import { Route as AppResearchRouteImport } from './routes/_app.research'
import { Route as AppPredictionsRouteImport } from './routes/_app.predictions'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppNewsRouteImport } from './routes/_app.news'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChartRouteImport } from './routes/_app.chart'
import { Route as AppChartIndexRouteImport } from './routes/_app.chart.index'
import { Route as AppChartTickerRouteImport } from './routes/_app.chart.$ticker'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenerRoute = AppScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsRoute = AppPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChartRoute = AppChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => AppRoute,
} as any)
const AppChartIndexRoute = AppChartIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChartRoute,
} as any)
const AppChartTickerRoute = AppChartTickerRouteImport.update({
  id: '/$ticker',
  path: '/$ticker',
  getParentRoute: () => AppChartRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chart': typeof AppChartRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/news': typeof AppNewsRoute
  '/portfolio': typeof AppPortfolioRoute
  '/predictions': typeof AppPredictionsRoute
  '/research': typeof AppResearchRoute
  '/screener': typeof AppScreenerRoute
  '/settings': typeof AppSettingsRoute
  '/chart/$ticker': typeof AppChartTickerRoute
  '/chart/': typeof AppChartIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/news': typeof AppNewsRoute
  '/portfolio': typeof AppPortfolioRoute
  '/predictions': typeof AppPredictionsRoute
  '/research': typeof AppResearchRoute
  '/screener': typeof AppScreenerRoute
  '/settings': typeof AppSettingsRoute
  '/chart/$ticker': typeof AppChartTickerRoute
  '/chart': typeof AppChartIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/chart': typeof AppChartRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/news': typeof AppNewsRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/predictions': typeof AppPredictionsRoute
  '/_app/research': typeof AppResearchRoute
  '/_app/screener': typeof AppScreenerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/chart/$ticker': typeof AppChartTickerRoute
  '/_app/chart/': typeof AppChartIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart'
    | '/dashboard'
    | '/news'
    | '/portfolio'
    | '/predictions'
    | '/research'
    | '/screener'
    | '/settings'
    | '/chart/$ticker'
    | '/chart/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/news'
    | '/portfolio'
    | '/predictions'
    | '/research'
    | '/screener'
    | '/settings'
    | '/chart/$ticker'
    | '/chart'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/chart'
    | '/_app/dashboard'
    | '/_app/news'
    | '/_app/portfolio'
    | '/_app/predictions'
    | '/_app/research'
    | '/_app/screener'
    | '/_app/settings'
    | '/_app/chart/$ticker'
    | '/_app/chart/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/screener': {
      id: '/_app/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof AppScreenerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research': {
      id: '/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predictions': {
      id: '/_app/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AppPredictionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chart': {
      id: '/_app/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof AppChartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chart/': {
      id: '/_app/chart/'
      path: '/'
      fullPath: '/chart/'
      preLoaderRoute: typeof AppChartIndexRouteImport
      parentRoute: typeof AppChartRoute
    }
    '/_app/chart/$ticker': {
      id: '/_app/chart/$ticker'
      path: '/$ticker'
      fullPath: '/chart/$ticker'
      preLoaderRoute: typeof AppChartTickerRouteImport
      parentRoute: typeof AppChartRoute
    }
  }
}

interface AppChartRouteChildren {
  AppChartTickerRoute: typeof AppChartTickerRoute
  AppChartIndexRoute: typeof AppChartIndexRoute
}

const AppChartRouteChildren: AppChartRouteChildren = {
  AppChartTickerRoute: AppChartTickerRoute,
  AppChartIndexRoute: AppChartIndexRoute,
}

const AppChartRouteWithChildren = AppChartRoute._addFileChildren(
  AppChartRouteChildren,
)

interface AppRouteChildren {
  AppChartRoute: typeof AppChartRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppNewsRoute: typeof AppNewsRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppPredictionsRoute: typeof AppPredictionsRoute
  AppResearchRoute: typeof AppResearchRoute
  AppScreenerRoute: typeof AppScreenerRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChartRoute: AppChartRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppNewsRoute: AppNewsRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppPredictionsRoute: AppPredictionsRoute,
  AppResearchRoute: AppResearchRoute,
  AppScreenerRoute: AppScreenerRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
